### ISSUE TITLE
About componentTemplateUrl

### ISSUE THREAD

**Issue by yudream** [apoterenko/ngx-dynamic-template#40]
Hi,
    Sorry for trouble you.
    I want to use componentTemplateUrl to get the template from restful api.
    My questions are:
    1. How to pass the token to backend when I call the restful api?
    2. Which data format should the backend provide? Just using string is OK, correct?
    3. Is there any examples could provide more detail info for this?
    4. Is this part using JitCompiler to compile the template, so I couldn't use this in AOT?
Thanks.

**Comment by apoterenko** [comment]
Hi!

I am gonna improve the demo and README

**Comment by apoterenko** [comment]
> 1. How to pass the token to backend when I call the restful api?
See updated demo/README

> 2. Which data format should the backend provide? Just using string is OK, correct?
See updated demo/README. You can parse response yourself

> 3. Is there any examples could provide more detail info for this?
See updated demo/README.

> 4. Is this part using JitCompiler to compile the template, so I couldn't use this in AOT?
<in progress..>

**Comment by yudream** [comment]
Hi,
    Thanks for your reply and your hard work. I am testing with ngx-dynamic-template.

**Comment by apoterenko** [comment]
You should pass the arguments inside your component like this way

  this.selectedComponent = `<jhi-test-a [bg]='bg'></jhi-test-a>`;

**Comment by yudream** [comment]
Thanks a lot. It's ok now in jit.
But in AOT, I found if i remove the @angular/compiler package the ngx-dynamic-template would throw error

<img width="1255" alt="wx20170525-145905 2x" src="https://cloud.githubusercontent.com/assets/5255465/26439528/311282e6-415b-11e7-9c26-38915e11963e.png">

**Comment by apoterenko** [comment]
Sorry, AoT does not support any more :(
