### ISSUE TITLE
Question: Loading Components From Lazy Loaded Modules?

### ISSUE THREAD

**Issue by Meligy** [apoterenko/ngx-dynamic-template#43]
Hello,
Sorry for putting this as an issue. I found this package while researching my options for a specific use case, so, if you may, I'd like to check with you if it's valid.

## Scenario

Imagine building an Angular CLI application that is a portal aggregating many data sources. When it loads, it asks the server what widgets it needs to show on the page, then it's supposed to use some dynamic loader to load these widgets.

It looks like it can be easily achieved if all the components were in the same module, but what I want to be ideally able to, is to have each of the component be their own lazy-loaded independent modules, that is only downloaded when the page decides it needs to load the relevant widget (Think of the modules like lazy-loaded routed modules, but with multiple modules in the same page).

### Question

The total list of widgets can be predefined (for example I can have a list of string templates that have the selectors for each component), but ideally the actual loading of the component and its module would be lazy in runtime.

Also having them in separate modules is essential as they are likely to be developed independently, and can have different services, etc. They'd still be in the same Angular CLI app for simplicity (so, not separate NPM modules or anything too crazy like that).

It looks like at least some part of this (like having components in separate modules, even if not lazy loading) can be achieved using this library, looking at `extraModules`. I'd appreciate it if you can draw some insight into that.

## Thanks

Sorry for asking a lot of things, while knowing 100% that you don't owe me or anyone else anything by releasing your great work to the world, quite the opposite actually. I definitely owe you so much gratitude for this awesome sharing.

Cheers,

**Comment by apoterenko** [comment]
Hi.

It's a valid useful feature. I did something like that at 2.1.5

**Comment by Meligy** [comment]
Thanks a lot.

By the way, you might want to keep the commit description on the first line to show up in the [commit log](https://github.com/apoterenko/ngx-dynamic-template/commits/master).

**Comment by Meligy** [comment]
It seems to be working very well in your demo.
THANKS.

I'll give it a try in a separate demo, then close this issue.

Cheers, you are beyond an amazing volunteer!

**Comment by Meligy** [comment]
Amazing.
It works!

You are officially my new open source hero :)
