### ISSUE TITLE
NgxDynamicTemplateModule is 'undefined'

### ISSUE THREAD

**Issue by inqunique** [apoterenko/ngx-dynamic-template#45]
Hi,
"Error: Unexpected value 'undefined' imported by the module 'AppModule'" is emitted when import "NgxDynamicTemplateModule".
 Please let me know what is my mistake.

[module.ts]
...
import { NgxDynamicTemplateModule } from 'ngx-dynamic-template';

@NgModule({
...
    imports: [NgxDynamicTemplateModule],
 ...
})

export class AppModule { }`

[systemjs.config.js]
...
            'ngx-dynamic-template': 'npm:ngx-dynamic-template/bundles/ngx-dynamic-component.umd.js'
...

[package.json]
`{
  ...
  },
  "dependencies": {
    "@angular/animations": "~4.1.3",
    "@angular/common": "~4.1.3",
    "@angular/compiler": "~4.1.3",
    "@angular/core": "~4.1.3",
    "@angular/flex-layout": "~2.0.0",
    "@angular/forms": "~4.1.3",
    "@angular/http": "~4.1.3",
    "@angular/material": "~2.0.0",
    "@angular/platform-browser": "~4.1.3",
    "@angular/platform-browser-dynamic": "~4.1.3",
    "@angular/router": "~4.1.3",
    "angular-in-memory-web-api": "~0.3.0",
    "bootstrap": "~3.3.7",
    "core-js": "~2.4.1",
    "hammerjs": "~2.0.8",
    "ngx-dynamic-template": "^2.1.14",
    "rxjs": "~5.4.0",
    "systemjs": "~0.20.12",
    "typescript": "^2.3.3",
    "zone.js": "~0.8.11"
  },
  "devDependencies": {
    "@types/node": "^7.0.22",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.1",
    "gulp-tsc": "^1.3.1",
    "gulp-typescript": "^3.1.6",
    "path": "^0.12.7",
    "typescript": "^2.3.3",
    "typings": "^2.1.1"
  }
}`

**Comment by apoterenko** [comment]
import { NgxDynamicTemplateModule } from 'ngx-dynamic-template/index';

**Comment by inqunique** [comment]
/ngx-dynamic-template/bundles/ngx-dynamic-component.umd.js/index Failed to load resource: the server responded with a status of 404 (Not Found) ...

**Comment by apoterenko** [comment]
Sorry for this issue. Pls check out 2.1.16

**Comment by MarkiEC13** [comment]
I'm still getting the same issue with 2.1.14. Let me know if I make any mistakes.
[module.ts]
import { NgxDynamicTemplateModule } from 'ngx-dynamic-template';

@NgModule({
...
imports: [NgxDynamicTemplateModule],
...
})

[systemjs.config.js]
...
'ngx-dynamic-template': 'npm:ngx-dynamic-template/bundles/ngx-dynamic-template.umd.js'
...

[package.json]
"@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/router": "4.1.3",
    "ngx-dynamic-template": "2.1.24",
    "ng2-bootstrap": "^1.4.0",
    "ng2-dragula": "^1.3.0",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.2",
    "systemjs": "0.19.27",
    "zone.js": "^0.8.4"
