### ISSUE TITLE
\' Unexpected identifier

### ISSUE THREAD

**Issue by AlbaLopez** [apoterenko/ngx-dynamic-template#47]
Good afternoon, when I put \' for example in '<span style=\'color: orange;\'>This is simple dynamic template</span>' I have the error Uncaught SyntaxError: Unexpected identifier
It is a project with Ionic 3 and angular 4.

Thank you!

**Comment by apoterenko** [comment]
escaping?

`\"'\"`

**Comment by AlbaLopez** [comment]
Can you give me an example with <a href="www.google.com">Google</a> ??

Thank you so much.

**Comment by apoterenko** [comment]
Could you provide more info? I don't understand the problem

**Comment by AlbaLopez** [comment]
Yes, of course,  <ng-template dynamic-template [template]="'<span>ALBA</span>'"> </ng-template> this works well, but if I want put a color, I  need to put <ng-template dynamic-template
 [template]="'<span style=\'color: orange;\'>This is simple dynamic template</span>'"></ng-template> with \' for quoted, but this don't works, If I put \' I have a the error Uncaught SyntaxError: Unexpected identifier because don't recognize the \'

**Comment by apoterenko** [comment]
`[template]="'<span style=\"color: orange;\">This is simple dynamic template'">`
?

**Comment by AlbaLopez** [comment]
I have the solution! I need to put \\' like --> <ng-template dynamic-template
[template]="'<span style=\\\\'color: orange;\\\\'>

**Comment by apoterenko** [comment]
good)
