### ISSUE TITLE
Cannot read property 'forRoot' of undefined

### ISSUE THREAD

**Issue by nishbat** [apoterenko/ngx-dynamic-template#49]
I am getting below error message

testpage:44 Error: (SystemJS) Cannot read property 'forRoot' of undefined
	TypeError: Cannot read property 'forRoot' of undefined
	    at execute (http://nitronet/app/../static/scripts/js/module.js:62:131)
	    at ZoneDelegate.invoke (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:391:26)
	Error loading http://nitronet/app/../static/scripts/js/boot.js
	    at execute (http://nitronet/app/../static/scripts/js/module.js:62:131)
	    at ZoneDelegate.invoke (http://nitronet/static/scripts/vendor/ang/zone.js/dist/zone.js:391:26)
	Error loading http://nitronet/app/../static/scripts/js/boot.js

at
imports: [http_1.HttpModule, platform_browser_1.BrowserModule, **ngx_dynamic_template_1.NgxDynamicTemplateModule.forRoot()**]

**Comment by apeter10** [comment]
I have the same issue.

**Comment by apoterenko** [comment]
import { NgxDynamicTemplateModule } from 'ngx-dynamic-template/index';

?

Can you provide steps for reproducing? Maybe some the demo starter? Thanks

**Comment by pukuotas** [comment]
I have the same error. I can't get out of it. Could you please help me. I did your steps in the main page.

**Comment by apoterenko** [comment]
Try append implicitly 

ngx-dynamic-template/**index**

**Comment by pukuotas** [comment]
this happens when i put 
```
 rxjs: {
        main:'Rx.js',
```

in to system.config.js. If I take it out, I got error 
`node_modules/rxjs/ 403 (Forbidden)`

So what is a better way to get out this issue?

Adding index like you said:

> Try append implicitly
> 
> ngx-dynamic-template/index


doesn't solve. The same happens like it were without it.
