### ISSUE TITLE
DOM issue

### ISSUE THREAD

**Issue by Yubz** [apoterenko/ngx-dynamic-template#53]
Hi,

Do you think it's possible to prevent adding in the DOM the parent node (`<div ng-dynamic-template-1>`) of my compiled component? 

![image](https://user-images.githubusercontent.com/6471303/32096345-7d803784-bb06-11e7-8e5c-999c8832ce20.png)

Thanks in advance for your help.

Yubz.

**Comment by apoterenko** [comment]
v2.2.3
