### ISSUE TITLE
How to use [routerLink]?

### ISSUE THREAD

**Issue by V1Ray** [apoterenko/ngx-dynamic-template#54]
How to use angular directive **routerLink**?

ts file:
```
htmlTemplate: string;

ngOnInit(): void {
       this.htmlTemplate = '<a routerLink="dress-options">link to user component1</a>';
 }
```
or
```
ngOnInit(): void {
       this.htmlTemplate = `<a [routerLink]="['dress-options']">link to user component</a>`;
}
```

html:
```
<ng-template dynamic-template
    [template]="htmlTemplate">
</ng-template>
```

**Comment by pierremalletneo9** [comment]
Same question has been answered on StackOverflow : 

https://stackoverflow.com/questions/47407908/angular-2-rendering-angular-html-components-from-webservice/47408849#47408849

Hope it helps

**Comment by apoterenko** [comment]
Thanks for your response. Yeah, he must include the extra module (RouterModule)
