### ISSUE TITLE
Upgrade to Angular 5

### ISSUE THREAD

**Issue by pratikpparikh** [apoterenko/ngx-dynamic-template#55]
Using old Http which is not compatible with Angular 5, this needs to be updated to HttpClient and HttpClientModule.

**Comment by apoterenko** [comment]
Thanks for your attention. HttpClientModule is also optional now (v2.2.2) (https://github.com/apoterenko/ngx-dynamic-template/commit/2846a4dc594647f826544fef2d1b92ce972ffd6a)
