### ISSUE TITLE
Bind a (click) to the template

### ISSUE THREAD

**Issue by AliF50** [apoterenko/ngx-dynamic-template#57]
I apologize if this is a repeat question but how can I bind say route = '<a (click) = "changeRoute()">Change Route</a>' to <ng-template dynamic-template
                             [template]="route">
                      </ng-template>

In the dom, it shows <a>Change Route</a>.

Looking forward to your response.

**Comment by apoterenko** [comment]
Sorry, but I don't understand the question. Can you plz more clearly?

**Comment by AliF50** [comment]
Hello, I don't need it resolved because I used a custom directive to get the job done.

But say if the template from the component is public template = '<a (click) = "someFunction()">Hello</a>';

And you want this string to be bound to the ng-template, how would you do it? Just doing it regularly resulted in <a>Hello</a>, in essence, the (click) event handler did not get bound to the HTML element.

**Comment by apoterenko** [comment]
Ok
