### ISSUE TITLE
TypeError: core_1.Injector.create is not a function (meteor-ionic3-angular4)

### ISSUE THREAD

**Issue by cankemik** [apoterenko/ngx-dynamic-template#58]
Hi, 
Trying with angular-ionic-meteor stack and can't seem to make it work.

imported like below:

`import { NgxDynamicTemplateModule } from 'ngx-dynamic-template/index';`

`imports: [
        BrowserModule,
        IonicModule.forRoot(MyApp),
        NgxDynamicTemplateModule.forRoot({ removeDynamicWrapper: true })
    ]`

HTML usage:
`<ng-template dynamic-template
                                     [template]="'<simple-input item-content></simple-input>'">
                        </ng-template>`

Error is like below:

`modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:32639 ERROR Error: Uncaught (in promise): TypeError: core_1.Injector.create is not a function
TypeError: core_1.Injector.create is not a function
    at DynamicDirective.DynamicBase (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:127939)
    at new DynamicDirective (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:127873)
    at createClass (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:42565)
    at createDirectiveInstance (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:42383)
    at createViewNodes (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:43831)
    at callViewAction (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:44280)
    at execComponentViewsAction (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:44189)
    at createViewNodes (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:43858)
    at createRootView (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:43726)
    at callWithDebugContext (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:45112)
    at DynamicDirective.DynamicBase (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:127939)
    at new DynamicDirective (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:127873)
    at createClass (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:42565)
    at createDirectiveInstance (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:42383)
    at createViewNodes (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:43831)
    at callViewAction (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:44280)
    at execComponentViewsAction (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:44189)
    at createViewNodes (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:43858)
    at createRootView (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:43726)
    at callWithDebugContext (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:45112)
    at resolvePromise (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:1170)
    at Object.reject (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:1147)
    at Tab.NavControllerBase._fireError (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:118163)
    at Tab.NavControllerBase._failed (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:118156)
    at modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:118203
    at ZoneDelegate.invoke (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:934)
    at Object.onInvoke (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:35509)
    at ZoneDelegate.invoke (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:933)
    at Zone.run (modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:816)
    at modules.js?hash=c758220b82bff811a2bec46978fb9adcc62825fb:1204`

Package.json

 `{
    "name": "meteor-app",
  "private": true,
  "scripts": {
    "start": "meteor run --settings private/settings.json"
  },
  "dependencies": {
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/compiler-cli": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@angular/platform-server": "4.4.4",
    "@ionic/storage": "1.1.7",
    "angular2-google-maps": "^0.17.0",
    "angular2-moment": "^1.1.0",
    "babel-runtime": "6.18.0",
    "bcrypt": "^1.0.3",
    "ionic-angular": "^3.8.0",
    "ionic-native": "2.2.11",
    "ionicons": "^3.0.0",
    "meteor-node-stubs": "~0.2.0",
    "meteor-rxjs": "^0.4.7",
    "moment": "^2.17.1",
    "ngx-dynamic-template": "^2.3.0",
    "nodemailer": "^2.7.2",
    "reflect-metadata": "^0.1.9",
    "rxjs": "5.0.0-beta.12",
    "sharp": "^0.17.1",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@types/meteor": "^1.3.31",
    "@types/meteor-accounts-phone": "0.0.5",
    "@types/meteor-collection-hooks": "^0.8.0",
    "@types/meteor-publish-composite": "0.0.32",
    "@types/underscore": "^1.7.36",
    "meteor-typings": "^1.3.1"
  }
 }`

**Comment by apoterenko** [comment]
Try v2.1.24 (angular4), v.2.3.0 is for angular5

**Comment by cankemik** [comment]
@apoterenko thanks for quick reply. i tried v2.1.24 still getting same the error.

`TypeError: core_1.Injector.create is not a function
    at DynamicDirective.DynamicBase`

**Comment by apoterenko** [comment]
npm install ngx-dynamic-template@2.1.24 --save

https://github.com/apoterenko/ngx-dynamic-template/commit/e903af0f77f6372c1af4ef93067890f675497260#diff-fd0d91017b022d14e891ec2a56f5277dL72

This is an error by 2.3.0 version (ReflectiveInjector.fromResolvedProviders - 2.1.24)

**Comment by cankemik** [comment]
@apoterenko oh sorry. i did a complete rebuild. delete all node_modules and meteor local and it worked. but i got a new error:
`modules.js?hash=b12a0401b2a0b21ba37bd4aad912e80c6bb8b748:32639 ERROR Error:Uncaught (in promise): Error: Template parse errors:
'simple-input' is not a known element:1. If 'simple-input' is an Angular component, then verify that it is part of this module.2. If 'simple-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<simple-input item-content></simple-input>"): ng:///dynamicComponentModule/dynamicComponentClass.html@0:0
Error: Template parse errors:
'simple-input' is not a known element:1. If 'simple-input' is an Angular component, then verify that it is part of this module.2. If 'simple-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppres`


I've tested the `<simple-input></simple-input>` component and it works when written statically in a component. Any ideas where i am wrong? 

Thanks for your time.

**Comment by apoterenko** [comment]
You should pass the component module via extraModules like this:


NgModule{ declarations: [SimpleInput]}
SimpleInputModule {
}

<ng-template dynamic-template
            [template]="'<simple-input></simple-input>'"
             [extraModules]="[SimpleInputModule]"></ng-template>

**Comment by cankemik** [comment]
@apoterenko `[extraModules]` was missing from directive i also added that but it seems it can't import module

add.ts

```
import {Component} from '@angular/core'; 
import {NavController,ActionSheetController,AlertController} from 'ionic-angular';
import {ModalService} from '../../services/modal';
import template from './add.html';
import {MultipleEntry} from "../multiple-entry/multiple-entry";
import {AddInputPage} from "../add-input/add-input";
import {SimpleInput} from '../../components/simple-input/simple-input';
@Component({
    selector: 'page-add',
    template: template,
    directives: [SimpleInput]
}
```

add.html
```
<ion-item>
    <ng-template dynamic-template
        [template]="'<simple-input item-content></simple-input>'"
        [extraModules]="[SimpleInput]">
    </ng-template>
</ion-item>
``` 

simple-input.ts
``` 
import {Component} from '@angular/core';
import template from './simple-input.html';

@Component({
    selector: 'simple-input',
    template: template
})
export class SimpleInput {
    constructor() {
    }
    ngAfterViewInit() {
        console.log("init");
    }
}
``` 
app.module.ts
``` 
...
import {SimpleInput} from '../components/simple-input/simple-input';
import {InputOptions} from '../components/options/options';

@NgModule({
    declarations: [
       ...,
        SimpleInput,
        InputOptions

    ],
    imports: [
        HttpModule,
        BrowserModule,
        IonicModule.forRoot(MyApp),
        NgxDynamicTemplateModule.forRoot({ removeDynamicWrapper: true })
    ]
...
``` 

and the error is:
``` 
ERROR Error: Uncaught (in promise): Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'
Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'
```

**Comment by apoterenko** [comment]
[extraModules]="[SimpleInput]"

it is for the module, but not for a component, it's angular pattern - each component exists within the module

 [extraModules]="[SimpleInputWrapperModule]"

**Comment by cankemik** [comment]
@apoterenko 
so sorry. i started recently work with this syntax and i'm not quite sure which way to go. i tried 2 options like

app.module.ts
```
...

@NgModule({
    declarations: [
        ...
        SimpleInput,
        InputOptions
    ],
    imports: [
        HttpModule,
        BrowserModule,
        IonicModule.forRoot(MyApp),
        NgxDynamicTemplateModule.forRoot({ removeDynamicWrapper: true })
    ],
    bootstrap: [IonicApp],
    entryComponents: [
        ....
    ],
    providers: [
        StatusBar,
        Splashscreen,
        ...
        {provide: ErrorHandler, useClass: IonicErrorHandler}
    ]
})
export class AppModule {}
```
```
[extraModules]="[AppModule]"
```

and also

```
import {Component,NgModule} from '@angular/core';
import template from './simple-input.html';

@Component({
    selector: 'simple-input',
    template: template
})
export class SimpleInput {
    constructor() {
    }

    ngAfterViewInit() {
        console.log("init");
    }
}


@NgModule({declarations: [SimpleInput]})
export class SimpleInputModule {
}
```

both of them returned 

```
Error: Uncaught (in promise): Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'
Error: Unexpected value 'undefined' imported by the module 'dynamicComponentModule'
```

am i missing something too easy?

**Comment by apoterenko** [comment]
import { SimpleInputModule } ..

AppComponent {

  extraModules = [SimpleInputModule];
}

AppComponent.html
[extraModules]="extraModules"

You forgot about component scope. See https://github.com/apoterenko/ngx-dynamic-template/blob/master/demo/src/app/dynamic/dynamic-holder.component.ts

**Comment by cankemik** [comment]
@apoterenko 

i managed to work it by importing the module

`import {SimpleInputModule} from '../../components/simple-input/simple-input';`

and 

```
export class AddPage {
    extraModules = [SimpleInputModule];
...
```

but it seems now i've lost the ability use ionic directives in component:
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ion-label' is not a known element:
1. If 'ion-label' is an Angular component, then verify that it is part of this module.
2. If 'ion-label' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ion-label stacked>NAME</ion-label> <ion-input type="text"></ion-input>"): ng:///SimpleInputModule/SimpleInput.html@0:0
'ion-input' is not a known element:
1. If 'ion-input' is an Angular component, then verify that it is part of this module.
2. If 'ion-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<ion-label stacked>NAME</ion-label> [ERROR ->]<ion-input type="text"></ion-input>"): ng:///SimpleInputModule/SimpleInput.html@0:36
Error: Template parse errors:
'ion-label' is not a known element:
1. If 'ion-label' is an Angular component, then verify that it is part of this module.
2. If 'ion-label' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ion-label stacked>NAME</ion-label> <ion-input type="text"></ion-input>"): ng:///SimpleInputModule/SimpleInput.html@0:0
'ion-input' is not a known element:
1. If 'ion-input' is an Angular component, then verify that it is part of this module.
2. If 'ion-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<ion-label stacked>NAME</ion-label> [ERROR ->]<ion-input type="text"></ion-input>"): ng:///SimpleInputModule/SimpleInput.html@0:36
```

I've tried rebuilding all the import arrays but the issue got bigger. Also tried them to gather all AppModule and then import AppModule all the way but it didn't do any good.  Do you think i should start from scratch?

**Comment by cankemik** [comment]
@apoterenko  managed to work it with

`@NgModule({declarations: [SimpleInput], imports: [IonicModule], exports: [SimpleInput]})`

thank you so much for this package and your help!

**Comment by apoterenko** [comment]
Good.
