### ISSUE TITLE
Template parse errors

### ISSUE THREAD

**Issue by SCBbestof** [apoterenko/ngx-dynamic-template#60]
Hello,

I'm trying to display HTML emails using ngx-dynamic-template and sometimes I get errors like this:

```
core.js:1427 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Void elements do not have end tags "hr" ("
<br>
<br>
[ERROR ->]</hr>
</td>
</tr>
"): ng:///_DynamicComponentModule/_DynamicComponent.html@57:0
Error: Template parse errors:
Void elements do not have end tags "hr" ("
<br>
<br>
[ERROR ->]</hr>
</td>
</tr>
"): ng:///_DynamicComponentModule/_DynamicComponent.html@57:0
```

Is there a way to ignore them and display the content even if it is poorly formatted? I want my clients to be able to read an email even if the sender screwed something within the HTML.

Thanks,
Bogdan

**Comment by apoterenko** [comment]
I am not sure, but you should try normalize an input html before using the tools like ngx-dynamic-template.
For example, there is a tool like https://github.com/fb55/htmlparser2
```

<div>Input <b>html</div>

=>

<div>Input <b>html</b></div>
```

**Comment by SCBbestof** [comment]
Thanks! I will take a look at that. I will close the issue.
