### ISSUE TITLE
ERROR in Error during template compile of 'AppModule'   Function calls are not supported in decorators but 'NgxDynamicTemplateModule' was called.

### ISSUE THREAD

**Issue by CosmoFruit** [apoterenko/ngx-dynamic-template#63]
in App.module
```
const ngxDynamicTemplateModuleForRoot = NgxDynamicTemplateModule.forRoot({
        extraModules: [SharedModules],
        removeDynamicWrapper: true,
    });

@NgModule({
    imports: [
       ngxDynamicTemplateModuleForRoot,
    ],
```

and build --prod 
i get 

> ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'NgxDynamicTemplateModule' was called.

**Comment by robbse** [comment]
The same problem here, since upgrading to Angular 6, ng-build with AOT fails. Any idea how to fix this?

**Comment by PsychoPflanze** [comment]
I'm sure that's already mentioned in the readme and on the npm page. You need to disable Angular AOT, which makes your application load around twice as long. I would really like to know, why i have to disable that in order to use this Module.

I need the functionality, but i will be looking for a better one.

**Comment by ngehlert** [comment]
@PsychoPflanze do you know an alternative? I also need this functionality, but this lib seems like the best from all I have tried

Are there any plans to get this running for angular 6?

**Comment by PsychoPflanze** [comment]
@ngehlert I've been using the basic angular Component Outlets, which requires you to have a component for everything you want to be dynamic, but it's fine.

**Comment by ngehlert** [comment]
@PsychoPflanze this is currently not an option as it would required really big change to the current structure. dang... why isn't there just a simple alternative like $compile in AngularJS :(
